apiVersion: dns.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Zone
metadata:
  name: yc-courses
spec:
  deletionPolicy: Orphan
  forProvider:
    folderIdRef:
      name: default
    name: yc-courses # укажи имя своей dns-зоны
    public: true
    zone: kalniyazov.ga. # укажи свою dns-зону