apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: default-ru-central1-a
spec:
  forProvider:
    folderIdRef:
      name: default
    networkIdRef:
      name: default
    v4CidrBlocks:
      - 10.128.0.0/24